name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
  push:
    branches:
      - main

jobs:
  commitlint:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: opensource-nepal/commitlint@v1

  luacheck:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt-get install -y luarocks
          sudo luarocks install luacheck
      - uses: jdx/mise-action@v2
      - run: mise run lint

  stylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: mise run fmt:check:lua


  llscheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable
      - name: Install Lua
        uses: leafo/gh-actions-lua@v12
        with:
          luaVersion: "luajit-openresty"
      - uses: jdx/mise-action@v2
      - name: Install luarocks
        uses: ColinKennedy/gh-actions-luarocks@v1.0.0
      - name: Download type stubs
        run: mise run deps:download
      - name: Install llscheck
        run: luarocks install llscheck
      - name: Run llscheck
        run: mise run llscheck
        env:
          LLSCHECK_CONFIG: .github/workflows/.luarc.json


  mdformat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: mise run fmt:check:md


  urlchecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: Install urlchecker
        run: uv tool install urlchecker

      - name: Check doc/
        run: uv tool run urlchecker check \
            --no-print --file-types .lua,.md,.txt,.vim,.yml \
            --retry-count 1 --timeout 5 doc/
      - name: Check lua/
        run: uv tool run urlchecker check \
            --no-print --file-types .lua,.md,.txt,.vim,.yml \
            --retry-count 1 --timeout 5 lua/
      - name: Check plugin/
        run: uv tool run urlchecker check \
            --no-print --file-types .lua,.md,.txt,.vim,.yml \
            --retry-count 1 --timeout 5 plugin/
      - name: Check spec/
        run: uv tool run urlchecker check \
            --no-print --file-types .lua,.md,.txt,.vim,.yml \
            --retry-count 1 --timeout 5 spec/
      - name: Check README.md
        run: uv tool run urlchecker check \
            --files README.md \
            --no-print --retry-count 1 --timeout 5 .
      - name: Check CONTRIBUTING.md
        run: uv tool run urlchecker check \
            --files CONTRIBUTING.md \
            --no-print --retry-count 1 --timeout 5 .
      - name: Check CHANGELOG.md
        run: uv tool run urlchecker check \
            --files CHANGELOG.md \
            --no-print --retry-count 1 --timeout 5 .
